### ISSUE TITLE
Feature request: Cut read position on the original read

### ISSUE THREAD

**Issue by FilipTomas** [at-cg/RAFT#3]
Hello,

First of all, thank you for this interesting tool. I've been using it to investigate the influence of read length on the contained read problem and I've ran into a problem. I can't seem to find the exact positions from which the cut read comes from in the original read. From looking at the code it seems that's only possible if the reads follow a specific naming scheme(if I understood your code correctly). Would it be possible to add this? 
E.g. if I have a read named long_read_1 cut into 2 shorter ones, currently I would get reads with names: read=1,long_read_1 and read=2,long_read_1, my suggestion would be to name the reads let's say read=1,pos=0:15000,long_read_1 and read=2,pos=15000:27200,long_read_1. Hope I made it clear enough.

Thank you in advance and kind regards!

**Comment by MehakBindra** [comment]
Thank you for the suggestion ! We have incorporated the change, and it is now available for download from the main branch.

**Comment by FilipTomas** [comment]
Thank you, works perfectly! :)
